### ISSUE TITLE
two types of explosivekind strife specibus

### ISSUE THREAD

**Issue by qwertyey** [jwright159/OverseerV2#3]
an explosivekind and exsplosivekind when making your specibus, can doom a player assuming the exsplosivekind isnt compatible with anything
![image](https://user-images.githubusercontent.com/74920136/163658411-a21511ae-5369-4f35-a9d5-11b916921cc7.png)

**Comment by jwright159** [comment]
I'm not seeing "exsplosivekind" listed anywhere
