### ISSUE TITLE
Inventory Page

### ISSUE THREAD

**Issue by aardwolf94** [jwright159/OverseerV2#4]
I tried to drop the pre-punched captchalogue card, and now the whole header bar UI is gone. Other pages/links are fine, just the inventory is unleavable unless I manually change the link.
![image](https://github.com/jwright159/OverseerV2/assets/39252564/e2d910ca-8ab4-4827-bd45-e6579b1125d7)

**Comment by jwright159** [comment]
Right click on the page, hit "view source", save that file, and send it. The error should be at the bottom, inside of the captchalogue dropdown.

**Comment by theocrati** [comment]
I'm having the same issue, except I have no items at all in my sylladex- the captcha card was the last item I removed cause I was trying to clean things up. I've also been unable to pick anything up *to* captchalogue, and logging out and logging in brought the UI back but not if I opened up the inventory

When I attempt to use any action to refresh the page, hitting the go button on use no item on nobody in particular, it seems to generator a blank card into my inventory, which I can then use, but the bug persists. 

[overseer inventory bug page source.txt](https://github.com/jwright159/OverseerV2/files/14156503/overseer.inventory.bug.page.source.txt)

**Comment by theocrati** [comment]
its suddenly not occurring any more?
